[package]

name = "modifier"
version = "0.0.2"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
description = "Fluid chaining APIs for both mutable ownership types."
readme = "README.md"
repository = "https://github.com/reem/rust-modifier"
license = "MIT"

[dev-dependencies]
stainless = "*"

